blueprints/auth.py
import string
import random

from flask import Blueprint, render_template, request, jsonify, redirect, url_for, session
from exts import mail, db
from flask_mail import Message
from models import EmailCaptchaModel, UserModel
from .forms import RegisterForm, LoginForm
# 用于对明文密码加密
from werkzeug.security import generate_password_hash, check_password_hash

bp = Blueprint("auth", __name__, url_prefix="/auth")


@bp.route("/login", methods=["GET", "POST"])
def login():
    if request.method == "GET":
        return render_template("login.html")
    else:
        form = LoginForm(request.form)
        if form.validate():
            email = form.email.data
            password = form.password.data
            user = UserModel.query.filter_by(email=email).first()
            if not user:
                print("邮箱不存在！")
                return redirect(url_for("auth.login"))
            if check_password_hash(user.password, password):
                # 在 cookie 存储登陆授权信息
                # flask 中的 session 是经过加密后存储在 cookie 中的
                session['user_id'] = user.id
                return redirect('/')
            else:
                print("密码错误！")
                return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.login"))


# GET：从服务器上读取数据
# POST：将客户端数据交给服务器
@bp.route("/register", methods=["POST", "GET"])
def register():
    if request.method == "GET":
        return render_template("register.html")
    else:
        # 验证用户提交的邮箱或验证码是否对应且正确
        form = RegisterForm(request.form)
        if form.validate():
            email = form.email.data
            username = form.username.data
            password = form.password.data
            user = UserModel(email=email, username=username, password=generate_password_hash(password))
            db.session.add(user)
            db.session.commit()
            # 实现向登陆页面的跳转
            return redirect(url_for("auth.login"))
        else:
            print(form.errors)
            return redirect(url_for("auth.register"))


@bp.route('/captcha')
def send_captcha():
    letters = string.ascii_letters + string.digits
    captcha = "".join(random.sample(letters, 4))
    email = request.args.get("email")
    message = Message(subject="验证码", recipients=[email], body=captcha)
    mail.send(message)
    # 将邮箱和验证码存入数据库
    email_captcha = EmailCaptchaModel(email=email, captcha=captcha)
    db.session.add(email_captcha)
    db.session.commit()
    return jsonify({'code': 200, 'msg': '验证码发送成功'})

@bp.route('logout')
def logout():
    session.clear()
    return redirect("/")

@bp.route("/mail/test")
def mail_test():
    message = Message(subject="邮箱测试", recipients=["18186126127@163.com"], body="这是一条测试邮件")
    mail.send(message)
    return "邮件发送成功！"

blueprints/qa.py
from flask import Blueprint, render_template, request, g, redirect, url_for
from .forms import QuestionForm, AnswerForm
from models import QuestionModel, AnswerModel
from exts import db
from decorators import login_required

bp = Blueprint("qa", __name__, url_prefix="/")


# qa 首页
@bp.route('/')
def index():
    questions = QuestionModel.query.order_by(QuestionModel.create_time.desc()).all()
    return render_template("index.html", questions=questions)


@bp.route('/publish', methods=['GET', 'POST'])
@login_required
def publish_qa():
    if request.method == 'GET':
        return render_template("publish_question.html")
    else:
        form = QuestionForm(request.form)
        if form.validate():
            title = form.title.data
            content = form.content.data
            question = QuestionModel(title=title, content=content, author=g.user)
            db.session.add(question)
            db.session.commit()
            return redirect("/")
        else:
            print(form.errors)
            return redirect(url_for("qa.publish_qa"))


@bp.route("/qa/detail/<qa_id>")
def question_detail(qa_id):
    question = QuestionModel.query.get(qa_id)
    return render_template("detail.html", question=question)


@bp.route("/answer/publish", methods=["POST"])
@login_required
def publish_answer():
    form = AnswerForm(request.form)
    if form.validate():
        content = form.content.data
        question_id = form.question_id.data
        answer = AnswerModel(content=content, question_id=question_id, author_id=g.user.id)
        db.session.add(answer)
        db.session.commit()
        return redirect(url_for("qa.question_detail", qa_id=question_id))
    else:
        print(form.errors)
        return redirect(url_for("qa.question_detail", qa_id=request.form.get("question_id")))


@bp.route("/search")
def search():
    q = request.args.get("q")
    questions = QuestionModel.query.filter(QuestionModel.title.contains(q)).all()
    return render_template("index.html", questions=questions)

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>{% block title %}

    {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static',filename="bootstrap/bootstrap.min.css") }}">
    <script src="{{ url_for('static',filename="jquery/jquery.3.6.min.js") }}"></script>
    <script src="{{ url_for('static',filename="bootstrap/bootstrap.min.js") }}"></script>
    <script src="{{ url_for('static',filename="bootstrap/bootstrap.bundle.min.js") }}"></script>
    <link rel="stylesheet" href="{{ url_for('static',filename="css/init.css") }}">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            -ms-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>
    <link rel="stylesheet" href="{{ url_for('static',filename="css/sticky-footer-navbar.css") }}">
    {% block head %}

    {% endblock %}
</head>
<body class="d-flex flex-column h-100">

<header>
    <!-- Fixed navbar -->
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
        <a class="navbar-brand" href="/">YOLO</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse"
                aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="/">主页 <span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{{ url_for("qa.publish_qa") }}">问答页面</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">我的视频</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">解析视频</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link disabled">待开发</a>
                </li>
                <li class="nav-item ml-4">
                    <form class="form-inline mt-2 mt-md-0" METHOD="get" action="{{ url_for("qa.search") }}">
                        <input class="form-control mr-sm-2" name="q" type="text" placeholder="搜索" aria-label="Search">
                        <button class="btn btn-outline-light my-2 my-sm-0" type="submit">搜索</button>
                    </form>
                </li>
            </ul>
            <ul class="navbar-nav mr-4">
                {% if user %}
                    <li class="nav-item active">
                        <a class="nav-link disabled" href="#">{{ user.username }} </a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for("auth.logout") }}">退出登录</a>
                    </li>
                {% else %}
                    <li class="nav-item active">
                        <a class="nav-link" href="{{ url_for('auth.login') }}">登录 <span
                                class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{{ url_for('auth.register') }}">注册</a>
                    </li>
                {% endif %}

            </ul>

        </div>
    </nav>
</header>


<div class="container" style="margin-top: 60px">
    {% block body %}

    {% endblock %}
</div>


<footer class="footer mt-auto  py-3">
    <div class="container">
        <span class="text-muted">本站内容仅供学习参考，请勿用于其他用途.</span>
    </div>
</footer>
</body>
</html>

templates/detail.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for("static",filename="css/detail.css") }}">
{% endblock %}
{% block title %}
    {{ question.title }}
{% endblock %}


{% block body %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10" style="background-color: #fff;padding: 20px;">
            <h3 class="page-title">{{ question.title }}</h3>
            <p class="question-info">
                <span>作者：{{ question.author.username }}</span>
                <span>时间：{{ question.create_time }}</span>
            </p>
            <hr>
            <p class="question-content">{{ question.content }}</p>
            <hr>
            <h4 class="comment-group-title">评论（{{ question.answers |length }}）：</h4>
            <form action="{{ url_for("qa.publish_answer") }}" method="post">
                <div class="form-group">
                    <input type="text" placeholder="请填写评论" name="content" class="form-control">
                    <input type="hidden" name="question_id" value="{{ question.id }}">
                </div>
                <div class="form-group" style="text-align: right;">
                    <button class="btn btn-primary">评论</button>
                </div>
            </form>
            <ul class="comment-group">
                {% for answer in question.answers %}



                    <li>
                        <div class="user-info">
                            <img class="avatar" src="{{ url_for("static",filename="images/cxk.jpg") }}" alt="">
                            <span class="username">{{ answer.author.username }}</span>
                            <span class="create-time">{{ answer.create_time }}</span>
                        </div>
                        <p class="comment-content">{{ answer.content }}</p>
                    </li>

                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/index.html
{% extends "base.html" %}
{% block head %}
    <link rel="stylesheet" href="{{ url_for("static",filename="css/index.css") }}">
{% endblock %}
{% block title %}
    首页
{% endblock %}
{% block body %}
    {% with messages = get_flashed_messages() %}
        {% if messages %}
            <ul class=flashes>
                {% for message in messages %}
                    <li>{{ message }}</li>
                {% endfor %}
            </ul>
        {% endif %}
    {% endwith %}
    <div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <ul class="question-ul">
                {% for question in questions %}

                    <li>
                        <div class="side-question">
                            <img class="side-question-avatar" src="{{ url_for("static",filename="/images/cxk.jpg") }}"
                                 alt="">
                        </div>
                        <div class="question-main">
                            <div class="question-title"><a
                                    href="{{ url_for("qa.question_detail",qa_id=question.id) }}">{{ question.title }}</a>
                            </div>
                            <div class="question-content">{{ question.content }}</div>
                            <div class="question-detail">
                                <span class="question-author">{{ question.username }}</span>
                                <span class="question-time">{{ question.create_time }}</span>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        <div class="col"></div>
    </div>
{% endblock %}

templates/login.html
{% extends "base.html" %}
{% block title %}
    登录
{% endblock %}
{% block head %}

{% endblock %}

{% block body %}
    <div class="row mt-4">
        <div class="col-sm"></div>
        <div class="col-sm">
            <form method="post" action="#">
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱地址</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" aria-describedby="emailHelp"
                           name="email">
                    <small id="emailHelp" class="form-text text-muted">我们不会将你的邮箱用于其他用途.</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>

                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger" role="alert">
                            {{ message }}
                        </div>
                    </div>
                {% endfor %}


                <button type="submit" class="btn btn-dark btn-block">登录</button>
            </form>
        </div>
        <div class="col-sm"></div>
    </div>

{% endblock %}

templates/publish_question.html
{% extends "base.html" %}
{% block title %}
    问答页面
{% endblock %}
{% block head %}

{% endblock %}

{% block body %}
<div class="row" style="margin-top: 20px;">
        <div class="col"></div>
        <div class="col-10">
            <h1 style="text-align: center;">发布问答</h1>
            <form action="#" method="post">
                <div class="form-group">
                    <input type="text" name="title" class="form-control" placeholder="请输入标题">
                </div>
                <div class="form-group">
                    <textarea name="content" class="form-control" rows="10" placeholder="请输入内容"></textarea>
                </div>
                <div class="form-group" style="text-align: right;">
                    <button class="btn btn-primary">发布</button>
                </div>
            </form>
        </div>
        <div class="col"></div>
    </div>

{% endblock %}

templates/register.html
{% extends "base.html" %}
{% block title %}
    注册
{% endblock %}
{% block head %}
    <script src="{{ url_for('static',filename="jquery/jquery.3.6.min.js") }}"></script>
    <script src="{{ url_for('static',filename="js/register.js") }}"></script>
{% endblock %}

{% block body %}
    <div class="row mt-4">
        <div class="col-sm"></div>
        <div class="col-sm">
            <form method="post" action="{{ url_for("auth.register") }}">
                {% for message in get_flashed_messages() %}
                    <div class="form-group">
                        <div class="text-danger" role="alert">
                            {{ message }}
                        </div>
                    </div>
                {% endfor %}
                <div class="form-group">
                    <label for="exampleInputEmail1">邮箱地址</label>
                    <input type="email" class="form-control" id="exampleInputEmail1" name="email"
                           aria-describedby="emailHelp">
                    <small id="emailHelp" class="form-text text-muted">我们不会将你的邮箱用于其他用途.</small>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">验证码</label>
                    <div class="input-group">
                        <input type="text" class="form-control" aria-describedby="emailHelp" name="captcha">
                        <div class="input-group-append">
                            <button class="btn btn-outline-secondary" type="button" id="captcha-btn">获取验证码</button>
                        </div>
                    </div>
                </div>
                <div class="form-group">
                    <label for="exampleInputEmail1">用户名</label>
                    <input type="text" class="form-control" name="username" aria-describedby="emailHelp">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">密码</label>
                    <input type="password" class="form-control" id="exampleInputPassword1" name="password">
                </div>
                <div class="form-group">
                    <label for="exampleInputPassword1">确认密码</label>
                    <input type="password" class="form-control" name="password_confirm">
                </div>

                <button type="submit" class="btn btn-dark btn-block">注册</button>
            </form>
        </div>
        <div class="col-sm"></div>
    </div>

{% endblock %}